title: Marta Forsberg
description: Composer, sound & light artist, violinist.
image_url: /assets/images/background.jpg
image_width: 999
image_height: 852
image_type: image/jpeg

# configuration

url: http://localhost:4000
locale: en_US

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
