title: Marta Forsberg
locale: en_US
description: Composer, sound and light artist, violinist. Based in Stockholm and Berlin.
url: http://localhost:4000

# Jekyll configuration

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
